repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: requirements-txt-fixer
      - id: file-contents-sorter
  - repo: 'https://github.com/keewis/blackdoc'
    rev: v0.3.8
    hooks:
      - id: blackdoc
  - repo: 'https://github.com/pycqa/flake8'
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=105, --extend-ignore=E203, --hang-closing]
        additional_dependencies: [flake8-bugbear==20.1.4]
  - repo: 'https://github.com/codespell-project/codespell'
    rev: v2.2.2
    hooks:
      - id: codespell
        args:
          - '--quiet-level=2'
          - '--uri-ignore-words-list=BA'
  - repo: 'https://github.com/asottile/pyupgrade'
    rev: v3.2.2
    hooks:
      - id: pyupgrade
        args:
          - '--py39-plus'
  - repo: 'https://github.com/asottile/add-trailing-comma'
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
  - repo: 'https://github.com/PyCQA/bandit'
    rev: 1.7.4
    hooks:
      - id: bandit
